const ERROR = "Error";
const OK = "OK";
const INVALID_TOKEN = "INVALID TOKEN";
const UINFIN_NOT_FOUND = "UINFIN NOT FOUND";
const PERSON_DATA_NOT_FOUND = "PERSON DATA NOT FOUND";
const INVALID_DATA_OR_SIGNATURE = "INVALID DATA OR SIGNATURE FOR PERSON DATA";
const ERROR_CONFIGURATION_PUBLIC_CERT_NOT_FOUND = 'Public cert not found';
const ERROR_CONFIGURATION_CLIENT_ID_NOT_FOUND = 'Client id not found';
const ERROR_CONFIGURATION_CLIENT_SECRET_NOT_FOUND = 'Client secret not found';
const ERROR_CONFIGURATION_REDIRECT_URL_NOT_FOUND = 'Redirect URL not found';
const ERROR_CONFIGURATION_CLIENT_SECURE_CERT_NOT_FOUND = 'Client secure cert not found';
const ERROR_CONFIGURATION_CLIENT_SECURE_CERT_PASSPHRASE_NOT_FOUND = 'Client passphrase not found';
const ERROR_CONFIGURATION_ENVIRONMENT_NOT_FOUND = 'Environment not found';
const ERROR_CONFIGURATION_TOKEN_URL_NOT_FOUND = "Token URL not found";
const ERROR_CONFIGURATION_PERSON_URL_NOT_FOUND = "Person URL not found";
const ERROR_CONFIGURATION_ATTRIBUTES_NOT_FOUND = "Attributes not found";
const ERROR_CONFIGURATION_PROXY_TOKEN_URL_NOT_FOUND = "Proxy Token URL not found";
const ERROR_CONFIGURATION_PROXY_PERSON_URL_NOT_FOUND = "Proxy Person URL not found";
const ERROR_UNKNOWN_AUTH_LEVEL = "Unknown Auth Level";
const ERROR_UNKNOWN_NOT_INIT = "Configurations not initialized";

const ENVIRONMENT = {
    SANDBOX: "SANDBOX",
    TEST: "TEST",
    PROD: "PROD"
};

const HTTP_METHOD = {
    GET: "GET",
    POST: "POST"
};

module.exports = {
    ERROR: ERROR,
    OK: OK,
    INVALID_TOKEN: INVALID_TOKEN,
    UINFIN_NOT_FOUND: UINFIN_NOT_FOUND,
    PERSON_DATA_NOT_FOUND: PERSON_DATA_NOT_FOUND,
    INVALID_DATA_OR_SIGNATURE: INVALID_DATA_OR_SIGNATURE,
    ENVIRONMENT: ENVIRONMENT,
    HTTP_METHOD: HTTP_METHOD,
    ERROR_CONFIGURATION_PUBLIC_CERT_NOT_FOUND,
    ERROR_CONFIGURATION_CLIENT_ID_NOT_FOUND,
    ERROR_CONFIGURATION_CLIENT_SECRET_NOT_FOUND,
    ERROR_CONFIGURATION_REDIRECT_URL_NOT_FOUND,
    ERROR_CONFIGURATION_CLIENT_SECURE_CERT_NOT_FOUND,
    ERROR_CONFIGURATION_CLIENT_SECURE_CERT_PASSPHRASE_NOT_FOUND,
    ERROR_CONFIGURATION_ENVIRONMENT_NOT_FOUND,
    ERROR_CONFIGURATION_TOKEN_URL_NOT_FOUND,
    ERROR_CONFIGURATION_PERSON_URL_NOT_FOUND,
    ERROR_CONFIGURATION_ATTRIBUTES_NOT_FOUND,
    ERROR_CONFIGURATION_PROXY_TOKEN_URL_NOT_FOUND,
    ERROR_CONFIGURATION_PROXY_PERSON_URL_NOT_FOUND,
    ERROR_UNKNOWN_AUTH_LEVEL,
    ERROR_UNKNOWN_NOT_INIT
};